//! Secondary mode: CMake dependency provider (CPP_PKG_IMPLEMENTATION.md §4).
//!
//! Two artifacts:
//! 1. `<pkg>Config.cmake` SHIM emitted from a manifest: recreates each
//!    component as an IMPORTED target (add_library(<name> STATIC|SHARED|
//!    INTERFACE IMPORTED GLOBAL)) with IMPORTED_LOCATION_<CONFIG>,
//!    INTERFACE_INCLUDE_DIRECTORIES, INTERFACE_COMPILE_DEFINITIONS/OPTIONS,
//!    INTERFACE_LINK_LIBRARIES (link_requires wrapped in $<LINK_ONLY:...>),
//!    INTERFACE_LINK_OPTIONS, INTERFACE_SOURCES, cxx_std ->
//!    INTERFACE_COMPILE_FEATURES cxx_std_NN. Also emits
//!    <pkg>ConfigVersion.cmake accepting any version (v0).
//!    ROUND-TRIP INVARIANT: probing an emitted shim must reproduce the
//!    manifest (extract -> emit -> extract fixpoint) — keep property spelling
//!    exactly what probe.rs reads.
//! 2. `cppkg_provider.cmake`: injected via CMAKE_PROJECT_TOP_LEVEL_INCLUDES,
//!    calls cmake_language(SET_DEPENDENCY_PROVIDER cppkg_provide
//!    SUPPORTED_METHODS FIND_PACKAGE). The provider shells out to
//!    `cpp-pkg provide --package <name> ...` which resolves/builds from the
//!    store and prints the shim directory; the provider then find_package's
//!    it (NO_DEFAULT_PATH) and marks the request satisfied. FetchContent
//!    interception: deferred (FIND_PACKAGE only in v0).

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{Component, ComponentKind, Manifest};
use crate::Result;

/// Emit `<find_name>Config.cmake` (+ ConfigVersion) into `dir`; returns the
/// directory to put on CMAKE_PREFIX_PATH.
pub fn write_config_shim(manifest: &Manifest, find_name: &str, dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(dir)?;

    let mut cfg = String::new();
    let _ = writeln!(
        cfg,
        "# Generated by cpp-pkg: Config.cmake shim for package '{}'.\n\
         # Recreates store-built components as IMPORTED targets. Do not edit.",
        manifest.package
    );
    for (name, component) in &manifest.components {
        emit_component(&mut cfg, name, component);
    }

    let config_path = dir.join(format!("{find_name}Config.cmake"));
    fs::write(&config_path, cfg)?;

    let version_path = dir.join(format!("{find_name}ConfigVersion.cmake"));
    fs::write(&version_path, config_version_content())?;

    Ok(dir.to_path_buf())
}

/// Emit the provider script; `cpp_pkg_bin` is the absolute path baked into
/// the script for shelling out.
pub fn write_provider_script(dir: &Path, cpp_pkg_bin: &Path) -> Result<PathBuf> {
    fs::create_dir_all(dir)?;
    let bin = escape_entry(&cpp_pkg_bin.to_string_lossy());
    let script = format!(
        r#"# Generated by cpp-pkg: CMake dependency provider.
# Inject with -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=<path to this file>.
if(CMAKE_VERSION VERSION_LESS "3.24")
  message(FATAL_ERROR "cpp-pkg dependency provider requires CMake >= 3.24 (have ${{CMAKE_VERSION}})")
endif()

# Macro, not function: the nested find_package() must set <pkg>_FOUND and the
# package's result variables in the scope that issued the original call.
macro(cppkg_provide method package_name)
  if("${{method}}" STREQUAL "FIND_PACKAGE")
    # Strict same-config propagation: the consumer's CMAKE_BUILD_TYPE decides
    # how the provided dependency is built (a Debug consumer must never link
    # Release store artifacts through the IMPORTED_CONFIGURATIONS fallback).
    # Empty means the consumer set no build type; cpp-pkg's release default
    # matches that single-config posture.
    set(_cppkg_cfg "${{CMAKE_BUILD_TYPE}}")
    if("${{_cppkg_cfg}}" STREQUAL "")
      set(_cppkg_cfg "release")
    endif()
    string(TOLOWER "${{_cppkg_cfg}}" _cppkg_cfg)
    execute_process(
      COMMAND "{bin}" provide --package "${{package_name}}" --project "${{CMAKE_SOURCE_DIR}}" --config "${{_cppkg_cfg}}"
      OUTPUT_VARIABLE _cppkg_shim_dir
      ERROR_VARIABLE _cppkg_stderr
      RESULT_VARIABLE _cppkg_exit
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _cppkg_exit EQUAL 0)
      message(FATAL_ERROR "cpp-pkg provide failed for package '${{package_name}}':\n${{_cppkg_stderr}}")
    endif()
    # BYPASS_PROVIDER keeps the nested find_package from re-entering this
    # provider; NO_DEFAULT_PATH pins resolution to the emitted shim.
    find_package(${{package_name}} CONFIG REQUIRED NO_DEFAULT_PATH
      PATHS "${{_cppkg_shim_dir}}" BYPASS_PROVIDER)
    unset(_cppkg_shim_dir)
    unset(_cppkg_stderr)
    unset(_cppkg_exit)
    unset(_cppkg_cfg)
  endif()
endmacro()

cmake_language(SET_DEPENDENCY_PROVIDER cppkg_provide SUPPORTED_METHODS FIND_PACKAGE)
"#
    );
    let path = dir.join("cppkg_provider.cmake");
    fs::write(&path, script)?;
    Ok(path)
}

fn config_version_content() -> &'static str {
    // v0: no solver consumes versions, so every requested version is
    // compatible. PACKAGE_VERSION_EXACT stays FALSE: an EXACT request is a
    // real constraint we cannot honestly claim to satisfy.
    "# Generated by cpp-pkg. v0: any requested version is accepted.\n\
     set(PACKAGE_VERSION \"0\")\n\
     set(PACKAGE_VERSION_COMPATIBLE TRUE)\n\
     set(PACKAGE_VERSION_EXACT FALSE)\n"
}

fn emit_component(out: &mut String, name: &str, component: &Component) {
    // UNKNOWN both for probed UNKNOWN imports and for components whose kind
    // was never recorded: CMake then treats any IMPORTED_LOCATION as a plain
    // link input, which is the safest reconstruction.
    let kind = match component.kind {
        Some(ComponentKind::Archive) => "STATIC",
        Some(ComponentKind::Dylib) => "SHARED",
        Some(ComponentKind::Interface) => "INTERFACE",
        Some(ComponentKind::Unknown) | None => "UNKNOWN",
    };

    let _ = writeln!(out, "\nif(NOT TARGET {name})");
    let _ = writeln!(out, "  add_library({name} {kind} IMPORTED GLOBAL)");

    // Per-config artifact locations. IMPORTED_CONFIGURATIONS is not probed
    // (harmless for the round trip) but lets CMake's config-fallback rules
    // pick a location when the consumer builds an unlisted config.
    let mut imported_configs: Vec<String> = Vec::new();
    for (config, path) in &component.location {
        let suffix = config.to_uppercase();
        set_property(
            out,
            name,
            &format!("IMPORTED_LOCATION_{suffix}"),
            &[escape_entry(&path.to_string_lossy())],
        );
        imported_configs.push(escape_entry(&suffix));
    }
    set_property(out, name, "IMPORTED_CONFIGURATIONS", &imported_configs);

    set_property(
        out,
        name,
        "INTERFACE_INCLUDE_DIRECTORIES",
        &escape_paths(&component.includes),
    );
    set_property(
        out,
        name,
        "INTERFACE_SYSTEM_INCLUDE_DIRECTORIES",
        &escape_paths(&component.system_includes),
    );

    let defines: Vec<String> = component
        .defines
        .iter()
        .map(|(key, value)| match value {
            Some(v) => escape_entry(&format!("{key}={v}")),
            None => escape_entry(key),
        })
        .collect();
    set_property(out, name, "INTERFACE_COMPILE_DEFINITIONS", &defines);

    let compile_options: Vec<String> = component
        .compile_options
        .iter()
        .map(|o| escape_entry(o))
        .collect();
    set_property(out, name, "INTERFACE_COMPILE_OPTIONS", &compile_options);

    if let Some(std) = component.cxx_std {
        set_property(
            out,
            name,
            "INTERFACE_COMPILE_FEATURES",
            &[format!("cxx_std_{std}")],
        );
    }

    // Frameworks ride INTERFACE_LINK_OPTIONS (not LINK_LIBRARIES): a plain
    // "-framework X" list entry there would reach the linker as one mangled
    // argument, and framework entries in LINK_LIBRARIES need either absolute
    // .framework paths or the FRAMEWORK genex, both fragile to reconstruct.
    // SHELL: is CMake's documented spelling for a space-separated option
    // group; it splits into two linker arguments at generate time.
    let mut link_options: Vec<String> = component
        .link_options
        .iter()
        .map(|o| escape_entry(o))
        .collect();
    for framework in &component.frameworks {
        link_options.push(escape_entry(&format!("SHELL:-framework {framework}")));
    }
    set_property(out, name, "INTERFACE_LINK_OPTIONS", &link_options);

    set_property(
        out,
        name,
        "INTERFACE_SOURCES",
        &escape_paths(&component.interface_sources),
    );

    // Order matters for the linker: requirements first, then raw artifact
    // paths, then system libs, then link-only edges.
    let mut link_libs: Vec<String> = Vec::new();
    for req in &component.requires {
        link_libs.push(escape_entry(req));
    }
    for path in &component.link_paths {
        link_libs.push(escape_entry(&path.to_string_lossy()));
    }
    for lib in &component.system_libs {
        // Bare name form: CMake itself lowers it to -l<name>. Tolerate an
        // already-prefixed entry rather than emitting a double prefix.
        let bare = lib.strip_prefix("-l").unwrap_or(lib);
        link_libs.push(escape_entry(bare));
    }
    for req in &component.link_requires {
        link_libs.push(format!("$<LINK_ONLY:{}>", escape_entry(req)));
    }
    set_property(out, name, "INTERFACE_LINK_LIBRARIES", &link_libs);

    let _ = writeln!(out, "endif()");
}

/// Write one `set_property` line; `entries` are already CMake-escaped.
/// Empty properties are skipped so probing a shim sees "unset", matching the
/// manifest's "empty list" (round-trip stability).
fn set_property(out: &mut String, target: &str, prop: &str, entries: &[String]) {
    if entries.is_empty() {
        return;
    }
    let joined = entries.join(";");
    let _ = writeln!(
        out,
        "  set_property(TARGET {target} PROPERTY {prop} \"{joined}\")"
    );
}

fn escape_paths(paths: &[PathBuf]) -> Vec<String> {
    paths
        .iter()
        .map(|p| escape_entry(&p.to_string_lossy()))
        .collect()
}

/// Escape one ;-list element for inclusion inside a quoted CMake argument.
/// `\;` encodes a literal semicolon within a single list element; `\$`
/// suppresses variable/genex expansion of user data (genexes we emit on
/// purpose, like $<LINK_ONLY:...>, are added around already-escaped content).
fn escape_entry(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            ';' => out.push_str("\\;"),
            '$' => out.push_str("\\$"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
// Test fixtures build Components field-by-field on purpose: the field list is
// long and only the populated fields matter to each assertion.
#[allow(clippy::field_reassign_with_default)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use std::process::Command;

    #[test]
    fn shim_escape_entry_rules() {
        assert_eq!(escape_entry("plain"), "plain");
        assert_eq!(escape_entry("a;b"), "a\\;b");
        assert_eq!(escape_entry("say \"hi\""), "say \\\"hi\\\"");
        assert_eq!(escape_entry("back\\slash"), "back\\\\slash");
        assert_eq!(escape_entry("$<FOO>"), "\\$<FOO>");
    }

    #[test]
    fn shim_config_version_accepts_anything() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = Manifest {
            package: "demo".into(),
            components: BTreeMap::new(),
            notes: Vec::new(),
        };
        let out = write_config_shim(&manifest, "demo", dir.path()).unwrap();
        assert_eq!(out, dir.path());
        let version = fs::read_to_string(dir.path().join("demoConfigVersion.cmake")).unwrap();
        assert!(version.contains("set(PACKAGE_VERSION_COMPATIBLE TRUE)"));
        assert!(dir.path().join("demoConfig.cmake").exists());
    }

    #[test]
    fn shim_provider_script_content() {
        let dir = tempfile::tempdir().unwrap();
        let bin = Path::new("/opt/tools/cpp-pkg");
        let path = write_provider_script(dir.path(), bin).unwrap();
        assert_eq!(path, dir.path().join("cppkg_provider.cmake"));
        let script = fs::read_to_string(&path).unwrap();
        assert!(script.contains(
            "cmake_language(SET_DEPENDENCY_PROVIDER cppkg_provide SUPPORTED_METHODS FIND_PACKAGE)"
        ));
        assert!(script.contains("macro(cppkg_provide method package_name)"));
        assert!(script.contains("\"/opt/tools/cpp-pkg\" provide --package"));
        assert!(script.contains("--project \"${CMAKE_SOURCE_DIR}\""));
        // Strict same-config propagation: the consumer's CMAKE_BUILD_TYPE
        // (lowercased, defaulted to release) reaches `cpp-pkg provide`.
        assert!(script.contains("--config \"${_cppkg_cfg}\""));
        assert!(script.contains("set(_cppkg_cfg \"${CMAKE_BUILD_TYPE}\")"));
        assert!(script.contains("string(TOLOWER \"${_cppkg_cfg}\" _cppkg_cfg)"));
        assert!(script.contains("set(_cppkg_cfg \"release\")"));
        assert!(script.contains("execute_process("));
        assert!(script.contains("message(FATAL_ERROR"));
        assert!(script.contains("${_cppkg_stderr}"));
        assert!(script.contains("NO_DEFAULT_PATH"));
        assert!(script.contains("BYPASS_PROVIDER"));
        assert!(script.contains("PATHS \"${_cppkg_shim_dir}\""));
    }

    fn demo_manifest() -> Manifest {
        let mut core = Component::default();
        core.kind = Some(ComponentKind::Archive);
        core.location = BTreeMap::from([
            ("Release".to_string(), PathBuf::from("/store/lib/libcore.a")),
            ("Debug".to_string(), PathBuf::from("/store/lib/libcore_d.a")),
        ]);
        core.includes = vec![
            PathBuf::from("/store/include"),
            PathBuf::from("/store/include2"),
        ];
        core.defines = vec![
            ("CORE_FLAG".to_string(), None),
            ("CORE_API".to_string(), Some(String::new())),
            ("CORE_VAL".to_string(), Some("1".to_string())),
            ("CORE_STR".to_string(), Some("\"hi\"".to_string())),
            ("CORE_LIST".to_string(), Some("a;b".to_string())),
        ];
        core.compile_options = vec!["-fno-rtti".to_string()];
        core.cxx_std = Some(20);
        core.link_options = vec!["-Wl,-dead_strip".to_string()];
        core.requires = vec!["demo::hdr".to_string()];
        core.link_requires = vec!["demo::hidden".to_string()];
        core.link_paths = vec![PathBuf::from("/opt/libs/libextra.a")];
        core.system_libs = vec!["z".to_string(), "-lcurl".to_string()];
        core.frameworks = vec!["CoreFoundation".to_string()];
        core.origin_find_name = "demo".to_string();

        let mut hdr = Component::default();
        hdr.kind = Some(ComponentKind::Interface);
        hdr.includes = vec![PathBuf::from("/store/include")];
        hdr.system_includes = vec![PathBuf::from("/store/sys")];
        hdr.interface_sources = vec![PathBuf::from("/store/src/extra.cpp")];
        hdr.origin_find_name = "demo".to_string();

        let mut hidden = Component::default();
        hidden.kind = Some(ComponentKind::Archive);
        hidden.location = BTreeMap::from([(
            "Release".to_string(),
            PathBuf::from("/store/lib/libhidden.a"),
        )]);
        hidden.origin_find_name = "demo".to_string();

        Manifest {
            package: "demo".to_string(),
            components: BTreeMap::from([
                ("demo::core".to_string(), core),
                ("demo::hdr".to_string(), hdr),
                ("demo::hidden".to_string(), hidden),
            ]),
            notes: Vec::new(),
        }
    }

    /// Round trip through a REAL cmake configure: find_package the emitted
    /// shim from a scratch project and dump raw target properties, asserting
    /// they match what the manifest declared (including $<LINK_ONLY:...>
    /// surviving unevaluated in INTERFACE_LINK_LIBRARIES).
    #[test]
    fn shim_roundtrip_cmake_properties() {
        let root = tempfile::tempdir().unwrap();
        let shim_dir = root.path().join("shim");
        let prefix = write_config_shim(&demo_manifest(), "demo", &shim_dir).unwrap();

        let src = root.path().join("proj");
        fs::create_dir_all(&src).unwrap();
        // LANGUAGES NONE: no compiler detection needed, we only read
        // properties back. Version 99.9 on find_package proves the
        // ConfigVersion file accepts any requested version.
        fs::write(
            src.join("CMakeLists.txt"),
            r#"cmake_minimum_required(VERSION 3.24)
project(shimscan LANGUAGES NONE)
find_package(demo 99.9 CONFIG REQUIRED)
string(ASCII 31 US)
set(out "${CMAKE_BINARY_DIR}/props.txt")
file(WRITE "${out}" "")
foreach(tgt demo::core demo::hdr demo::hidden)
  foreach(prop TYPE IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_DEBUG
      INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
      INTERFACE_COMPILE_DEFINITIONS INTERFACE_COMPILE_OPTIONS
      INTERFACE_COMPILE_FEATURES INTERFACE_LINK_LIBRARIES
      INTERFACE_LINK_OPTIONS INTERFACE_SOURCES)
    get_target_property(v ${tgt} ${prop})
    file(APPEND "${out}" "${tgt}${US}${prop}${US}${v}\n")
  endforeach()
endforeach()
"#,
        )
        .unwrap();

        let build = root.path().join("build");
        let output = Command::new("cmake")
            .arg("-S")
            .arg(&src)
            .arg("-B")
            .arg(&build)
            .arg("-G")
            .arg("Ninja")
            .arg(format!("-DCMAKE_PREFIX_PATH={}", prefix.display()))
            .output()
            .expect("failed to spawn cmake; is it on PATH?");
        assert!(
            output.status.success(),
            "cmake configure failed\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );

        let props_raw = fs::read_to_string(build.join("props.txt")).unwrap();
        let mut props: BTreeMap<(String, String), String> = BTreeMap::new();
        for line in props_raw.lines() {
            let mut fields = line.split('\u{1F}');
            let tgt = fields.next().unwrap().to_string();
            let prop = fields.next().unwrap().to_string();
            let value = fields.next().unwrap_or("").to_string();
            props.insert((tgt, prop), value);
        }
        let get = |tgt: &str, prop: &str| -> &str {
            props
                .get(&(tgt.to_string(), prop.to_string()))
                .map(String::as_str)
                .unwrap_or_else(|| panic!("missing dumped property {tgt}/{prop}"))
        };

        assert_eq!(get("demo::core", "TYPE"), "STATIC_LIBRARY");
        assert_eq!(
            get("demo::core", "IMPORTED_LOCATION_RELEASE"),
            "/store/lib/libcore.a"
        );
        assert_eq!(
            get("demo::core", "IMPORTED_LOCATION_DEBUG"),
            "/store/lib/libcore_d.a"
        );
        assert_eq!(
            get("demo::core", "INTERFACE_INCLUDE_DIRECTORIES"),
            "/store/include;/store/include2"
        );
        // Manifest declaration order preserved; the quote survives verbatim
        // and the embedded semicolon stays escaped as one list element.
        assert_eq!(
            get("demo::core", "INTERFACE_COMPILE_DEFINITIONS"),
            "CORE_FLAG;CORE_API=;CORE_VAL=1;CORE_STR=\"hi\";CORE_LIST=a\\;b"
        );
        assert_eq!(get("demo::core", "INTERFACE_COMPILE_OPTIONS"), "-fno-rtti");
        assert_eq!(get("demo::core", "INTERFACE_COMPILE_FEATURES"), "cxx_std_20");
        // requires, then link_paths, then system_libs (bare, -l stripped),
        // then link_requires wrapped in LINK_ONLY — surviving unevaluated.
        assert_eq!(
            get("demo::core", "INTERFACE_LINK_LIBRARIES"),
            "demo::hdr;/opt/libs/libextra.a;z;curl;$<LINK_ONLY:demo::hidden>"
        );
        assert_eq!(
            get("demo::core", "INTERFACE_LINK_OPTIONS"),
            "-Wl,-dead_strip;SHELL:-framework CoreFoundation"
        );

        assert_eq!(get("demo::hdr", "TYPE"), "INTERFACE_LIBRARY");
        assert_eq!(
            get("demo::hdr", "INTERFACE_INCLUDE_DIRECTORIES"),
            "/store/include"
        );
        assert_eq!(
            get("demo::hdr", "INTERFACE_SYSTEM_INCLUDE_DIRECTORIES"),
            "/store/sys"
        );
        assert_eq!(get("demo::hdr", "INTERFACE_SOURCES"), "/store/src/extra.cpp");
        // Unset properties read back as <var>-NOTFOUND: empty manifest lists
        // must NOT emit empty properties (round-trip stability).
        assert_eq!(get("demo::hdr", "INTERFACE_LINK_LIBRARIES"), "v-NOTFOUND");

        assert_eq!(get("demo::hidden", "TYPE"), "STATIC_LIBRARY");
        assert_eq!(
            get("demo::hidden", "IMPORTED_LOCATION_RELEASE"),
            "/store/lib/libhidden.a"
        );
    }
}
